
package introsde.dsantoro.pcws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "pcwsService", targetNamespace = "http://pcws.dsantoro.introsde/", wsdlLocation = "http://192.168.5.3:6905/ws/pcws?wsdl")
public class PcwsService
    extends Service
{

    private final static URL PCWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException PCWSSERVICE_EXCEPTION;
    private final static QName PCWSSERVICE_QNAME = new QName("http://pcws.dsantoro.introsde/", "pcwsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.5.3:6905/ws/pcws?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PCWSSERVICE_WSDL_LOCATION = url;
        PCWSSERVICE_EXCEPTION = e;
    }

    public PcwsService() {
        super(__getWsdlLocation(), PCWSSERVICE_QNAME);
    }

    public PcwsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PCWSSERVICE_QNAME, features);
    }

    public PcwsService(URL wsdlLocation) {
        super(wsdlLocation, PCWSSERVICE_QNAME);
    }

    public PcwsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PCWSSERVICE_QNAME, features);
    }

    public PcwsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PcwsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Pcws
     */
    @WebEndpoint(name = "PcwsImplPort")
    public Pcws getPcwsImplPort() {
        return super.getPort(new QName("http://pcws.dsantoro.introsde/", "PcwsImplPort"), Pcws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Pcws
     */
    @WebEndpoint(name = "PcwsImplPort")
    public Pcws getPcwsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pcws.dsantoro.introsde/", "PcwsImplPort"), Pcws.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PCWSSERVICE_EXCEPTION!= null) {
            throw PCWSSERVICE_EXCEPTION;
        }
        return PCWSSERVICE_WSDL_LOCATION;
    }

}
